const request = require("supertest");
const express = require("express");
const mongoose = require("mongoose");
require("dotenv").config();

const authRoutes = require("../routes/authRoutes");
const ticketRoutes = require("../routes/ticketRoutes");
const bugRoutes = require("../routes/bugRoutes");
const { errorHandler } = require("../middleware/errorMiddleware");

const app = express();
app.use(express.json());
app.use("/api/auth", authRoutes);
app.use("/api/tickets", ticketRoutes);
app.use("/api/bugs", bugRoutes);
app.use(errorHandler);

describe("Bug Report Lifecycle Integration Tests", () => {
  let adminToken = "";
  let ticketId = "";
  let bugId = "";

  beforeAll(async () => {
    if (mongoose.connection.readyState === 0) {
      await mongoose.connect(process.env.MONGO_URI);
    }
    const loginRes = await request(app).post("/api/auth/login").send({
      email: "sudhir3116@gmail.com",
      password: "Password123!",
    });
    adminToken = loginRes.body.accessToken;

    // Create a source ticket
    const ticketRes = await request(app)
      .post("/api/tickets")
      .set("Authorization", `Bearer ${adminToken}`)
      .send({
        title: "Source Ticket for Bug Test",
        description: "Bug report integration test ticket.",
        category: "Software",
      });
    ticketId = ticketRes.body.ticket._id;
  });

  afterAll(async () => {
    await mongoose.connection.close();
  });

  test("POST /api/bugs — Create Bug Report from Ticket", async () => {
    const res = await request(app)
      .post("/api/bugs")
      .set("Authorization", `Bearer ${adminToken}`)
      .send({
        ticketId,
        title: "Bug: Jest Automated Bug Report",
        description: "Generated by automated Jest test runner.",
        severity: "High",
      });

    expect(res.statusCode).toBe(201);
    expect(res.body.bug).toHaveProperty("bugNumber");
    bugId = res.body.bug._id;
  });

  test("PUT /api/bugs/:id — Update Bug Status to In Progress", async () => {
    const res = await request(app)
      .put(`/api/bugs/${bugId}`)
      .set("Authorization", `Bearer ${adminToken}`)
      .send({ status: "In Progress" });

    expect(res.statusCode).toBe(200);
    expect(res.body.bug).toHaveProperty("status", "In Progress");
  });
});
